name: Deploy React App to S3

on:
  push:
    branches:
      - main  # change to 'master' if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # use your app's Node version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build React app
      - name: Build React App
        run: npm run build

      # Step 5a: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 5b: Deploy to S3 using AWS CLI
      - name: Deploy to S3
        run: aws s3 sync build/ s3://raynx-frontend --delete

      # Step 6 (Optional): Invalidate CloudFront cache
      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v1
        with:
          distribution: E1F2M0ZFTHRU0M # <-- replace with CloudFront ID if using
          paths: '/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
